name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click
  push:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: HalleyAssist/actions-fork-sync@master
        with:
          retry_after: 1